### ISSUE TITLE
SSL Error Bad Cert

### ISSUE THREAD

**Issue by fabolhak** [joc-gafo/blog#3]
Because there is no proper CONTRIBUTIONS.md and no issue template, I will just format this issue free style 😜.

**Expected behaviour**:
The JOC-gafo blog should be a safe space with modern security mechanisms to protect my precious privacy.

**Current behaviour**:
I get triggered by an "Insecure Connection" warning from my favorite Web-Browser. In order to get the indispensable news and exciting recipes from JOC I have to add the website to my exception list. The website functionality seems to work normally, however I feel unprotected and unsafe during my visit ☹. This is not the experience I would expect from a website with such a high reputation.

**First occured**: 
Unix Timestamp: 1507018604

**Steps to reproduce**:
- turn on your computer / smartphone / smartwatch
- start your favorite webbrowser
- type `joc-gafo.org` (without www) in the url bar
- press enter

**Environment**: 
Tested on
- Android 7.1.2 (Build: 26 Sep) with Firefox 55.0.2
- Ubuntu 16.04.3 (Kernel: 4.5.2-040502-generic) with Firefox 55.0.3
- Ipad Safari

![screenshot_2017-10-03_09-47-44](https://user-images.githubusercontent.com/20029691/31116001-baf81f2c-a824-11e7-8381-a5fc03c84e08.png)

**Comment by Phibedy** [comment]
For the future we should make sure that the internet is a safe place and websites forcing people into bad security behavior should be punished by work. Free food for poor students :shallow_pan_of_food:

**Comment by mp4096** [comment]
Thank you for reporting this issue. It should be fixed by now. Please check it out!
